/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AcidenteDao;
import controller.conn;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Acidente;
import model.PessoaAcidenteM;
import model.UsuarioM;

/**
 *
 * @author joelmir
 */
public class Principal extends javax.swing.JFrame {
    AcidenteDao Adao = new AcidenteDao() {};
    GerarTabela getab = new GerarTabela();
    
    int Buscar_M = -1;
    int Buscar_V = -1;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_principal_ = new javax.swing.JPanel();
        jdp_principal = new javax.swing.JDesktopPane();
        jButton_cadastrar_ = new javax.swing.JButton();
        jButton_fechar_ = new javax.swing.JButton();
        jLabel_TITULO = new javax.swing.JLabel();
        jLabel_DESCRICAO = new javax.swing.JLabel();
        jTextField_descricaoAcidente = new javax.swing.JTextField();
        jLabel_data = new javax.swing.JLabel();
        jTextField_data = new javax.swing.JTextField();
        jLabel_danos = new javax.swing.JLabel();
        jTextField_danosVeiculo = new javax.swing.JTextField();
        jLabel_Loxalizacao = new javax.swing.JLabel();
        jLabel_rodovia = new javax.swing.JLabel();
        jTextField_rodovia = new javax.swing.JTextField();
        jLabel_uf = new javax.swing.JLabel();
        jTextField_UF = new javax.swing.JTextField();
        jLabel_municipio = new javax.swing.JLabel();
        jTextField_municipio = new javax.swing.JTextField();
        jLabel_descricaoLocalizacao = new javax.swing.JLabel();
        jTextField_descricaoLocalizacao = new javax.swing.JTextField();
        jLabel_motorista = new javax.swing.JLabel();
        jLabel_CPFvitima = new javax.swing.JLabel();
        jButton_BuscarMotorista_ = new javax.swing.JButton();
        jButton_BuscarVitima_ = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Consultar = new javax.swing.JMenu();
        jMenuItem_ConsultarCPF_ = new javax.swing.JMenuItem();
        jMenuItem_Veiculo_ = new javax.swing.JMenuItem();
        jMenuItem_Acidente_ = new javax.swing.JMenuItem();
        jMenuItem_Usuario_ = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas Joelmir");
        setResizable(false);

        javax.swing.GroupLayout jPanel_principal_Layout = new javax.swing.GroupLayout(jPanel_principal_);
        jPanel_principal_.setLayout(jPanel_principal_Layout);
        jPanel_principal_Layout.setHorizontalGroup(
            jPanel_principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel_principal_Layout.setVerticalGroup(
            jPanel_principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jdp_principal.setBackground(java.awt.SystemColor.activeCaption);
        jdp_principal.setForeground(new java.awt.Color(51, 51, 51));
        jdp_principal.setName(""); // NOI18N

        jButton_cadastrar_.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton_cadastrar_.setText("Cadastrar");
        jButton_cadastrar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrar_ActionPerformed(evt);
            }
        });

        jButton_fechar_.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton_fechar_.setText("Fechar");
        jButton_fechar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fechar_ActionPerformed(evt);
            }
        });

        jLabel_TITULO.setText("CADASTRO ACIDENTES VEICULOS:");

        jLabel_DESCRICAO.setText("Descricao Acidente:");

        jLabel_data.setText("Data:");

        jLabel_danos.setText("Danos Veiculo:");

        jLabel_Loxalizacao.setText("LOCALIZACAO DO VEICULO:");

        jLabel_rodovia.setText("Rodovia:");

        jLabel_uf.setText("UF:");

        jLabel_municipio.setText("Municipio:");

        jLabel_descricaoLocalizacao.setText("Descrição Localização:");

        jLabel_motorista.setText("Motorista(Informe CPF):");

        jLabel_CPFvitima.setText("Vitima Acidente(Informe CPF):");

        jButton_BuscarMotorista_.setText("Buscar Motorista");
        jButton_BuscarMotorista_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarMotorista_ActionPerformed(evt);
            }
        });

        jButton_BuscarVitima_.setText("Buscar Vitima");
        jButton_BuscarVitima_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarVitima_ActionPerformed(evt);
            }
        });

        jdp_principal.setLayer(jButton_cadastrar_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_fechar_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_TITULO, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_DESCRICAO, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_descricaoAcidente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_data, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_data, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_danos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_danosVeiculo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_Loxalizacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_rodovia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_rodovia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_uf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_UF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_municipio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_municipio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_descricaoLocalizacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_descricaoLocalizacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_motorista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_CPFvitima, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_BuscarMotorista_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_BuscarVitima_, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdp_principalLayout = new javax.swing.GroupLayout(jdp_principal);
        jdp_principal.setLayout(jdp_principalLayout);
        jdp_principalLayout.setHorizontalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_DESCRICAO)
                                    .addComponent(jLabel_data)
                                    .addComponent(jLabel_danos)
                                    .addComponent(jLabel_motorista))
                                .addGap(99, 99, 99)
                                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_rodovia, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_descricaoLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_danosVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_data)
                                    .addComponent(jTextField_descricaoAcidente)
                                    .addComponent(jButton_BuscarVitima_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_BuscarMotorista_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_descricaoLocalizacao)
                            .addComponent(jLabel_municipio)
                            .addComponent(jLabel_uf)
                            .addComponent(jLabel_rodovia)
                            .addComponent(jLabel_CPFvitima)
                            .addComponent(jLabel_Loxalizacao)))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(jButton_fechar_, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jButton_cadastrar_, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(438, Short.MAX_VALUE))
        );
        jdp_principalLayout.setVerticalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addComponent(jLabel_TITULO)
                        .addGap(21, 21, 21)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_DESCRICAO)
                            .addComponent(jTextField_descricaoAcidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_data)
                            .addComponent(jTextField_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel_danos)
                        .addGap(26, 26, 26)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_motorista)
                            .addComponent(jButton_BuscarMotorista_)))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addComponent(jTextField_danosVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGap(26, 26, 26)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_CPFvitima)
                    .addComponent(jButton_BuscarVitima_))
                .addGap(43, 43, 43)
                .addComponent(jLabel_Loxalizacao)
                .addGap(18, 18, 18)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addComponent(jLabel_rodovia)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel_uf))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addComponent(jTextField_rodovia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(18, 18, 18)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_municipio)
                    .addComponent(jTextField_municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_descricaoLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_descricaoLocalizacao))
                .addGap(18, 18, 18)
                .addComponent(jButton_cadastrar_, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_fechar_)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jMenu_Consultar.setText("Consultar");
        jMenu_Consultar.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N

        jMenuItem_ConsultarCPF_.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jMenuItem_ConsultarCPF_.setText("Consultar CPF");
        jMenuItem_ConsultarCPF_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarCPF_ActionPerformed(evt);
            }
        });
        jMenu_Consultar.add(jMenuItem_ConsultarCPF_);

        jMenuItem_Veiculo_.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jMenuItem_Veiculo_.setText("Veiculo");
        jMenuItem_Veiculo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Veiculo_ActionPerformed(evt);
            }
        });
        jMenu_Consultar.add(jMenuItem_Veiculo_);

        jMenuItem_Acidente_.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jMenuItem_Acidente_.setText("Acidente");
        jMenuItem_Acidente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Acidente_ActionPerformed(evt);
            }
        });
        jMenu_Consultar.add(jMenuItem_Acidente_);

        jMenuItem_Usuario_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_Usuario_.setText("Usuario/Funcionario");
        jMenuItem_Usuario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Usuario_ActionPerformed(evt);
            }
        });
        jMenu_Consultar.add(jMenuItem_Usuario_);

        jMenuBar1.add(jMenu_Consultar);

        jMenu1.setText("Cadastrar Pessoa");
        jMenu1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_principal_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdp_principal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdp_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_principal_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cadastrar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrar_ActionPerformed
       
        Acidente aa = this.CadastroAcidente();
        Adao.inserir(aa);
       
        limpar();
      
    }//GEN-LAST:event_jButton_cadastrar_ActionPerformed

    private void jButton_fechar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fechar_ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_fechar_ActionPerformed

    private void jButton_BuscarMotorista_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarMotorista_ActionPerformed
        
        
        String CPF = JOptionPane.showInputDialog("Informe o CPF");
        String sqlId = "SELECT idpessoa FROM Pessoa WHERE cpf = ?";
        
        try {
            PreparedStatement ps = conn.getConexao().prepareStatement(sqlId);
            ps.setString(1, CPF);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                Buscar_M = rs.getInt("idpessoa");
                JOptionPane.showMessageDialog(null, "Busca Confirmada!");
            }else{
                JOptionPane.showMessageDialog(null, "CPF Não Cadastrado!\nTente Novamente. ");
            }
            
            ps.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro SQL: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton_BuscarMotorista_ActionPerformed

    private void jButton_BuscarVitima_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarVitima_ActionPerformed
        
        String CPF = JOptionPane.showInputDialog("Informe o CPF");
        String sqlId = "SELECT idpessoa FROM Pessoa WHERE cpf = ?";
        
        try {
            PreparedStatement ps = conn.getConexao().prepareStatement(sqlId);
            ps.setString(1, CPF);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                Buscar_V = rs.getInt("idpessoa");
                JOptionPane.showMessageDialog(null, "Busca Confirmada ");
            }
            
            ps.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "CPF Não Cadastrado! " + ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton_BuscarVitima_ActionPerformed

    private void jMenuItem_ConsultarCPF_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarCPF_ActionPerformed
       
        ConsultarPessoa cp = new ConsultarPessoa();
        jdp_principal.add(cp);
        cp.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_ConsultarCPF_ActionPerformed

    private void jMenuItem_Veiculo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Veiculo_ActionPerformed
        
        ConsultarVeiculo cv = new ConsultarVeiculo();
        jdp_principal.add(cv);
        cv.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_Veiculo_ActionPerformed

    private void jMenuItem_Acidente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Acidente_ActionPerformed

        ConsultarAcidente ca = new ConsultarAcidente();
        jdp_principal.add(ca);
        ca.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem_Acidente_ActionPerformed

    private void jMenuItem_Usuario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Usuario_ActionPerformed
        
        ConsultarUsuario c = new ConsultarUsuario();
        jdp_principal.add(c);
        c.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_Usuario_ActionPerformed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
       
        PessoaV v = new PessoaV();
        jdp_principal.add(v);
        v.setVisible(true);
        
    }//GEN-LAST:event_jMenu1MousePressed

    public void limpar(){
        
         jTextField_descricaoAcidente.setText("");
         jTextField_data.setText("");
         jTextField_danosVeiculo.setText("");
         jTextField_rodovia.setText("");
         jTextField_UF.setText("");
         jTextField_municipio.setText("");
         jTextField_descricaoLocalizacao.setText("");
       
     }
     
    public Acidente CadastroAcidente(){
        
        Acidente a = new Acidente();
        a.setDescricaoAcidente(jTextField_descricaoAcidente.getText());
        a.setDataAcidente(jTextField_data.getText());
        a.setDanos(jTextField_danosVeiculo.getText());
        a.setMotorista(Buscar_M);
        a.setVitima(Buscar_V);
        a.setRodovia(jTextField_rodovia.getText());
        a.setUF(jTextField_UF.getText());
        a.setMunicipio(jTextField_municipio.getText());
        a.setDescricaoLocalizacao(jTextField_descricaoLocalizacao.getText());
        return a;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_BuscarMotorista_;
    private javax.swing.JButton jButton_BuscarVitima_;
    private javax.swing.JButton jButton_cadastrar_;
    private javax.swing.JButton jButton_fechar_;
    private javax.swing.JLabel jLabel_CPFvitima;
    private javax.swing.JLabel jLabel_DESCRICAO;
    private javax.swing.JLabel jLabel_Loxalizacao;
    private javax.swing.JLabel jLabel_TITULO;
    private javax.swing.JLabel jLabel_danos;
    private javax.swing.JLabel jLabel_data;
    private javax.swing.JLabel jLabel_descricaoLocalizacao;
    private javax.swing.JLabel jLabel_motorista;
    private javax.swing.JLabel jLabel_municipio;
    private javax.swing.JLabel jLabel_rodovia;
    private javax.swing.JLabel jLabel_uf;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Acidente_;
    private javax.swing.JMenuItem jMenuItem_ConsultarCPF_;
    private javax.swing.JMenuItem jMenuItem_Usuario_;
    private javax.swing.JMenuItem jMenuItem_Veiculo_;
    private javax.swing.JMenu jMenu_Consultar;
    private javax.swing.JPanel jPanel_principal_;
    private javax.swing.JTextField jTextField_UF;
    private javax.swing.JTextField jTextField_danosVeiculo;
    private javax.swing.JTextField jTextField_data;
    private javax.swing.JTextField jTextField_descricaoAcidente;
    private javax.swing.JTextField jTextField_descricaoLocalizacao;
    private javax.swing.JTextField jTextField_municipio;
    private javax.swing.JTextField jTextField_rodovia;
    private javax.swing.JDesktopPane jdp_principal;
    // End of variables declaration//GEN-END:variables
}
